# Generated by Django 5.0.7 on 2024-09-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imdb_score_movie_imdb_votes_movie_tmdb_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_score',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_votes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_score',
        ),
    ]
